version: '3'
services:
  app:
    build: .
    ports:
      - "8026:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db 
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sister_v0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3311:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8098:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: